### ISSUE TITLE
Nothing gets passed to authelia-basic-2fa

### ISSUE THREAD

**Issue by dsuni** [ViRb3/authelia-basic-auth-2fa#1]
Using the setup provided it seems no traffic gets passed to authelia-basic-2fa. When using the configuration provided, the only requests to get passed to a-b-2fa are requests to /auth but the only requests to actually arrive to nginx are GET requests for the /api/verify location, which then get passed directly to authelia making it as if a-b-2fa wasn't even there. Attempting to pass the /api location to a-b-2fa only results in "unrecognized auth header format" errors.

Is there something about the configuration that I'm missing? I'm using authelia-basic-2fa_2.0.13 and authelia v4.22.0 on Debian Buster (no docker involved).

**Comment by dsuni** [comment]
Okay... The issue was that authelia-basic-2fa is to be configured differently than authelia. For authelia you configure:
location /authelia {
    ...
    proxy_pass http://authelia:9091/api/verify;

but for authelia-basic-2fa you need to configure:
location /authelia {
    ...
    proxy_pass http://authelia:8081/; # no /api/verify here

This was... less than obvious from the documentation.

**Comment by ViRb3** [comment]
Hello and thanks for the feedback. I updated the documentation and incorporated your suggestion.
